# Generated by Django 3.2.6 on 2022-06-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripcion producto')),
                ('precio', models.IntegerField(verbose_name='Precio producto')),
                ('nuevo', models.BooleanField(verbose_name='Estado producto')),
                ('fecha_fabricacion', models.DateField(verbose_name='Fecha fabricacion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.marca')),
            ],
        ),
    ]
