# Generated by Django 3.2.6 on 2022-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(verbose_name='Nuevo'),
        ),
    ]
