# Generated by Django 3.2.6 on 2022-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_marca_id_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre contactante')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo contactante')),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']], verbose_name='Motivo de contacto')),
                ('mensaje', models.TextField(blank=True, max_length=100, verbose_name='Mensaje')),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
