# Generated by Django 3.2.6 on 2022-06-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
