# Generated by Django 3.2.6 on 2022-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_categoriass_productoww'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fundacion', models.CharField(max_length=50, verbose_name='Nombre Fundacion')),
                ('rut_fundacion', models.CharField(max_length=50, verbose_name='Rut Fundacion')),
                ('foto_imagen', models.ImageField(null=True, upload_to='productos')),
                ('cuenta_fundacion', models.IntegerField(verbose_name='Numero de cuenta')),
            ],
        ),
    ]
