# Generated by Django 3.2.6 on 2022-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0011_refugios2_users1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugios3',
            fields=[
                ('id_refugio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID_Fundacion')),
                ('nombre_refugio', models.CharField(max_length=50, verbose_name='Nombre de Refugio')),
                ('descripcion_refugio', models.CharField(max_length=60, verbose_name='Descripcion de refugio')),
                ('imagen_refugio', models.ImageField(null=True, upload_to='productos')),
                ('cuenta_refugio', models.IntegerField(verbose_name='Cuenta de fundacion')),
                ('rut_refugio', models.CharField(max_length=70, verbose_name='Rut de fundacion')),
            ],
        ),
    ]
